### ISSUE TITLE
git pushするとエラーが発生する問題

### ISSUE THREAD

**Issue by oyui7272** [Hiromichi5/teamD#1]
git pushをしようと試みたところ以下のエラーが発生しました．
1枚目がgithubに表示されるエラー，2枚目がコンソールに表示されるエラーです．

<img width="1506" alt="Pasted Graphic" src="https://github.com/Hiromichi5/teamD/assets/83291418/6860bbe5-f017-474a-ab03-6814eb19d189">

<img width="930" alt="スクリーンショット 2024-01-11 13 44 41" src="https://github.com/Hiromichi5/teamD/assets/83291418/e230bb3e-96b4-4775-9ffc-093e7a5c6f2b">

**Comment by Hiromichi5** [comment]
アクセス権付与したので、また試してみてください！

**Comment by oyui7272** [comment]
ありがとうございます！
無事pushすることができました，

branchを分けずに作業してしまっていたので，mainブランチにマージしました．
