### ISSUE TITLE
お菓子の詳細データに関する質問

### ISSUE THREAD

**Issue by oyui7272** [Hiromichi5/teamD#3]
お疲れ様です．
お菓子の詳細データに関して，以下2つについて質問があります．

**1. 値段について**
現在データベースに登録されている値段データの型は何でしょうか？
値段に関する情報をポップアップで表示した際，小数点第1位まで表示されてしまう問題があります．データベース登録時からint型になるよう設定いただくことは可能でしょうか？

**2. 商品紹介URL, タグ，コメントについて**
商品紹介URL，タグ，コメントがほとんどのお菓子の場合，データが取得されず表示されないようです．こちらは正しい動作でしょうか？
どのデータも表示がない場合，detail.htmlのポップアップに表示しないよう削除することも可能ですが，いかがでしょうか？

よろしくお願いいたします．

**Comment by Hiromichi5** [comment]
お疲れ様です．以下解答です．

1. 値段について
値段がint型になるよう修正しました．

2. 商品紹介URL, タグ，コメントについて
READ.mdの属性名が間違えていたので修正しました．
htmlファイルは現状のままで大丈夫です．正常に出力されると思います．

**Comment by oyui7272** [comment]
ありがとうございます！
承知しました！

今確認したところ，まだ小数点第一位まで表示されてしまう問題とURL，タグ，コメントが表示されない問題がありました🥲

**Comment by Hiromichi5** [comment]
自分の場合だと、リポジトリに上がってるやつでちゃんと表示されてます...
あれ、お菓子いな〜

![Uploading スクリーンショット 2024-01-15 14.23.13.png…]()

**Comment by Hiromichi5** [comment]
自分の場合だと、リポジトリに上がってるやつでちゃんと表示されてます...
あれ、お菓子いな〜
何かわかれば連絡します！

<img width="606" alt="スクリーンショット 2024-01-15 14 23 13" src="https://github.com/Hiromichi5/teamD/assets/152363273/a7b5037d-f3ad-4250-aecc-73eedee88667">

**Comment by oyui7272** [comment]
こちらの不手際でした，申し訳ございません！

git pullで最新情報の取得ができてなかったみたいです🥲🙏
反映されていることが確認できました！

ありがとうございます！！
