### ISSUE TITLE
フロントエンド検討事項

### ISSUE THREAD

**Issue by Hiromichi5** [Hiromichi5/teamD#4]
発表資料作成中に思ったことをまとめておきます。
時間があまりないので、修正は出来ればで大丈夫です！

【SNSランキング】
・画像に比べて、順位といいねの文字が小さい？
・SNSランキングも詳細見れるようにする？
・ランキングの画像で、width=300,height=300と設定したので、無理やり正方形に変形されている(３位の画像)
<img width="750" alt="スクリーンショット 2024-01-15 15 53 13" src="https://github.com/Hiromichi5/teamD/assets/152363273/54e5f9af-6809-4108-98c5-4dd77296346a">

【最新情報】
・どのお菓子が最新なのかわかりにくい？(左上が最新であることが伝わらないかも)
登録日不要って書いてたけど、見えるようにした方が良かったかも...ごめん🙇‍♂️

<img width="815" alt="スクリーンショット 2024-01-15 15 54 02" src="https://github.com/Hiromichi5/teamD/assets/152363273/eb5a18f4-5826-482b-bf49-198b84439dec">

**Comment by oyui7272** [comment]
教えてくれてありがとうございます！！気づいていなかった 🙇‍♀️ 
以下3点対応しました！（fix_design_homeブランチの最新にアップしています）

### ❇️ 対応したこと
【SNSランキング】
1. 画像に比べて、順位といいねの文字が小さい 
→ 大きくしました
2. ランキングの画像で、width=300,height=300と設定したので、無理やり正方形に変形されている(３位の画像)
→ 無理やりにならないように修正しました

【最新情報】

3. どのお菓子が最新なのかわかりにくい？(左上が最新であることが伝わらないかも)
→ モーダル表示には追加できました．詳細画面になぜか表示されないですが...(detail.htmlの68行目)
　　 **ちなみに，Readmeの登録日の表おそらくdateかな？**


### ❇️ 今後について

・SNSランキングも詳細見れるようにする → 火曜日中に修正します！

**Comment by Hiromichi5** [comment]
早い対応ありがとうございます！
おっしゃる通り、登録日はdataではなくてdateです🙇‍♂️

**Comment by oyui7272** [comment]
こちら全ての対応完了し，mainブランチにマージしました！

**Comment by Hiromichi5** [comment]
ありがとう！
コメントのタグも消えてとても見やすくなりました✨
